version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: nyc_taxi_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nyc_taxi
      POSTGRES_USER: nyc_user
      POSTGRES_PASSWORD: nyc_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nyc_user -d nyc_taxi"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
